### ISSUE TITLE
How to change the camera parameters of my own data

### ISSUE THREAD

**Issue by YananSunn** [boycehbz/MvSMPLfitting#6]
Thanks for releasing this great code.

I want to run this code on my own data and follow the steps below.

Step 1:
I changed the 3DOH50K_Parameters.txt with the parameters below.
As for the intrinsics, I printed the chessboard and took several pictures with the two cameras. Then I used python `cv2.calibrateCamera` to calculate the intrinsics.
As for the extrinsic, I took several pairs of pictures with the two cameras together. Then I used Matlab stereoCameraCalibrator tool to calculate the extrinsic.
The camera parameters are like:
```
0
1143.74746 0.0 939.105073 
0.0 1141.28573 543.456349 
0.0 0.0 1.0 
0 0
1.0 0.0 0.0 0.0 
0.0 1.0 0.0 0.0 
0.0 0.0 1.0 0.0

1
5066.92807 0.0 2590.96622 
0.0 5061.26346 1715.91466 
0.0 0.0 1.0 
0 0
0.998061327884789 -0.002655953070809 -0.062181441718073 -479.0757512146067
0.0005705478583129127 -0.999437508887020 -0.033531184065716 450.0474335522135
0.062235522461001 0.033430700605779 0.997501442605981 104.3606041755306
```

Step 2:
I changed the JSON data.
I ran OpenPose on the pictures taken from different views to get to 2d keypoints and map them to the COCO17-order to generate the keypoints JSON.

Step 3:
I changed the images.
I replaced the images with my own images and rename them as the demo does.

Step 4:
I ran the code, but the results are bad.
![$~553@_ )@BGVH8}Z6 TUB1](https://user-images.githubusercontent.com/44168292/133877894-5b88926d-6d31-4bf4-b9f9-443dd8f73345.png)
![U3P9DZPS27ZLBH6NL2MLX6N](https://user-images.githubusercontent.com/44168292/133877901-9db94111-2c7b-462e-b61e-2bbf8ac7252b.png)

When I ran the code with one view, which means the camera parameters are:
```
0
2000 0 h/2
0 2000 w/2
0 0 1
0 0
1 0 0 0
0 1 0 0
0 0 1 0
```
as you mentioned in issue 2. The results are better.
![RPQ`1@F3Y@XTP36LC{L$QF0](https://user-images.githubusercontent.com/44168292/133878070-86b517ae-760a-48b7-9f84-7e99535f663b.png)
![SK@9WP_J9V4TJP3ZR7 9J32](https://user-images.githubusercontent.com/44168292/133878075-5223a124-760d-4189-a7a1-e244740b921d.png)

I guess the camera parameters are not correct but I have no idea how to fix it. Could you please offer me some advice? Thanks a lot!

**Comment by boycehbz** [comment]
The intrinsic camera parameters seem problematic since the focal lens are obviously different.
You can try to visualize the initial result in Line 146 of '''code/utils/init_guess.py''' to check that the camera parameters are correct. (If the cameras are correct, the re-projected human is close to the 2D keypoints.)
